<?php
function executeGitPull()
{
    // Execute the git pull command
    $output = [];
    $return_var = 0;

    // log the current user to see if the user is www-data
    exec('whoami', $output, $return_var);

    $command = 'cd ' . get_template_directory();
    if (isset($_GET['branch'])) {
        $command .= ' && git checkout ' . $_GET['branch'];
    }
    $command .= ' && git pull';

    exec($command);

    // Print the output of the git pull command
    foreach ($output as $line) {
        echo $line . PHP_EOL . '<br>';
    }

    // Check if there was an error
    if ($return_var !== 0) {
        handleGitPullError($output);
    } else {
        echo "Successfully pulled the latest changes." . PHP_EOL;
    }
}

function handleGitPullError($output)
{
    $error_message = implode(PHP_EOL, $output);

    if (strpos($error_message, 'Permission denied (publickey)') !== false) {
        echo 'It looks like there is an issue with your SSH keys.' . PHP_EOL;
        echo 'To fix this, try the following steps:' . PHP_EOL;
        echo '1. Ensure you have an SSH key generated by running: ssh-keygen -t rsa -b 4096 -C "your_email@example.com"' . PHP_EOL;
        echo '2. Add your SSH key to the ssh-agent:' . PHP_EOL;
        echo '   - Start the ssh-agent in the background: eval "$(ssh-agent -s)"' . PHP_EOL;
        echo '   - Add your SSH key to the ssh-agent: ssh-add ~/.ssh/id_rsa' . PHP_EOL;
        echo '3. Add your SSH key to your GitHub account:' . PHP_EOL;
        echo '   - Copy the SSH key to your clipboard: pbcopy < ~/.ssh/id_rsa.pub' . PHP_EOL;
        echo '   - Go to GitHub > Settings > SSH and GPG keys > New SSH key, and paste your key.' . PHP_EOL;
    } elseif (strpos($error_message, 'fatal: unable to access') !== false) {
        echo 'It looks like there is an issue with your network or repository URL.' . PHP_EOL;
        echo 'To fix this, try the following steps:' . PHP_EOL;
        echo '1. Ensure you have a stable internet connection.' . PHP_EOL;
        echo '2. Check if the repository URL is correct and accessible.' . PHP_EOL;
        echo '3. If you are behind a proxy, configure git to use the proxy:' . PHP_EOL;
        echo '   git config --global http.proxy http://proxyuser:proxypassword@proxy.server.com:port' . PHP_EOL;
    } else {
        echo 'An unexpected error occurred. Please check the output above for more details.' . PHP_EOL;
    }
}

if (isset($_GET['sync_git'])) {
    executeGitPull();
    die;
}
